[vlive]
title = "BTS ─ Star Board"
url = "https://www.vlive.tv/channel/FE619/board/3498?lang=ko"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
contentSelector = "span[class^='upload_time']"
waitUntil = "networkidle"
onFail = "stale"

[vlive_notice]
title = "BTS ─ Notice"
url = "https://www.vlive.tv/channel/FE619/board/35?lang=ko"
entrySelector = "li[class^='post_item']"
titleSelector = "strong"
linkSelector = "a[class^='post_area']"
imageSelector = "span[class^='covered_image']"
contentSelector = "span[class^='upload_time']"
waitUntil = "networkidle"
onFail = "stale"

[naverpost_bighit_bts]
title = "빅히트 뮤직 ─ BTS"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=615210&memberNo=51325039"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"
